<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SEOStore.Application\SEOStore.Application.csproj" />
    <ProjectReference Include="..\SEOStore.Infrastructure\SEOStore.Infrastructure.csproj" />
    <ProjectReference Include="..\SEOStore.Shared\SEOStore.Shared.csproj" />
    <ProjectReference Include="..\SEOStore.Domain\SEOStore.Domain.csproj" />
    
  </ItemGroup>

</Project>